use srpagodb;

SET sql_mode = '';

CREATE TABLE gas_station (
ID NVARCHAR(30) primary key not null,
RAZON_SOCIAL NVARCHAR(255),
CALLE NVARCHAR(255),
RFC NVARCHAR(20),
COLONIA NVARCHAR(255),
CODIGO_POSTAL NVARCHAR(255),
DATE_INSERT NVARCHAR(128),
PERMISO_ID NVARCHAR(8),
NUMERO_PERMISO NVARCHAR(255),
FECHA_APLICACION NVARCHAR(128),
LONGITUD DECIMAL(15,10),
LATITUD DECIMAL(15,10),
REGULAR_PRICE DECIMAL(7,2),
PREMIUM_PRICE DECIMAL(7,2),
DIESEL_PRICE DECIMAL(7,2),
CREATED_AT timestamp default current_timestamp,
UPDATED_AT timestamp default current_timestamp
);

CREATE TABLE card_holder (
ID NVARCHAR(255) primary key not null,
NAME NVARCHAR(255),
LAST_NAME NVARCHAR(255),
CREATED_AT timestamp default current_timestamp,
UPDATED_AT timestamp default current_timestamp
);

CREATE TABLE bank_payment_card (
ID NVARCHAR(40) primary key not null,
CARD_NUMBER NVARCHAR(20),
EXPIRATION_YEAR NVARCHAR(4),
EXPIRATION_MONTH NVARCHAR(2),
CREATED_AT timestamp default current_timestamp,
UPDATED_AT timestamp default current_timestamp
);

CREATE TABLE gas_sell(
ID NVARCHAR(40) primary key not null,
CARD_HOLDER_ID NVARCHAR(40),
BANK_PAYMENT_CARD_ID NVARCHAR(40),
GAS_STATION_ID NVARCHAR(30),
GAS_TYPE NVARCHAR(1),
AMOUNT decimal(10,4),
SELLER_NAME NVARCHAR(255),
CREATED_AT timestamp default current_timestamp,
UPDATED_AT timestamp default current_timestamp
);

#IF EVERITHING GOES OK THEN UNCOMMENT NEXT LINE FOR COMMIT and COMMENT ROLLBACK LINE
COMMIT;
#IF SOMETHING GOES WRONG THEN UNCOMMENT NEXT LINE FOR ROLLBACK and COMMENT COMMIT LINE
#rollback;
