use srpagodb;

SET sql_mode = '';

CREATE TABLE gas_station (
ID VARCHAR(30) primary key not null,
RAZON_SOCIAL VARCHAR(255),
CALLE VARCHAR(255),
RFC VARCHAR(20),
COLONIA VARCHAR(255),
CODIGO_POSTAL VARCHAR(255),
DATE_INSERT VARCHAR(128),
PERMISO_ID VARCHAR(8),
NUMERO_PERMISO VARCHAR(255),
FECHA_APLICACION VARCHAR(128),
LONGITUD DECIMAL(15,10),
LATITUD DECIMAL(15,10),
REGULAR_PRICE DECIMAL(7,2),
PREMIUM_PRICE DECIMAL(7,2),
DIESEL_PRICE DECIMAL(7,2),
CREATED_AT timestamp default current_timestamp,
UPDATED_AT timestamp default current_timestamp
);

CREATE TABLE card_holder (
ID VARCHAR(255) primary key not null,
NAME VARCHAR(255),
LAST_NAME VARCHAR(255),
CREATED_AT timestamp default current_timestamp,
UPDATED_AT timestamp default current_timestamp
);

CREATE TABLE bank_payment_card (
ID VARCHAR(40) primary key not null,
CARD_NUMBER VARCHAR(20),
EXPIRATION_YEAR VARCHAR(4),
EXPIRATION_MONTH VARCHAR(2),
CREATED_AT timestamp default current_timestamp,
UPDATED_AT timestamp default current_timestamp
);

CREATE TABLE gas_sell(
ID VARCHAR(40) primary key not null,
CARD_HOLDER_ID VARCHAR(40),
BANK_PAYMENT_CARD_ID VARCHAR(40),
GAS_STATION_ID VARCHAR(30),
GAS_TYPE VARCHAR(1),
AMOUNT decimal(10,4),
SELLER_NAME VARCHAR(255),
CREATED_AT timestamp default current_timestamp,
UPDATED_AT timestamp default current_timestamp
);

#IF EVERITHING GOES OK THEN UNCOMMENT NEXT LINE FOR COMMIT and COMMENT ROLLBACK LINE
COMMIT;
#IF SOMETHING GOES WRONG THEN UNCOMMENT NEXT LINE FOR ROLLBACK and COMMENT COMMIT LINE
#rollback;
